/*
 * AccessPanel.java
 *
 * Created on 15 ottobre 2006, 11.11
 */

package it.unibo.homemanager.userinterfaces;

import it.unibo.homemanager.util.*;
import it.unibo.homemanager.tablemap.*;
import it.unibo.homemanager.dbmanagement.*;
import it.unibo.homemanager.dbmanagement.dbexceptions.*;

import alice.tucson.api.*;
import alice.logictuple.*;
import it.unibo.homemanager.ServiceFactory;
import it.unibo.homemanager.tablemap.ServicesInterfaces.UserServiceInterface;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  admin
 */
public class AccessPanel extends javax.swing.JPanel {
    
    private TucsonTupleCentreId tid, rbac, casa;
    private Database db;
    private UserServiceInterface us;
    private User usr = null;
    private int rId,sId;

    private MainPanel mp;
    private TracePanel tp;
    
    /** Creates new form AccessPanel */
    public AccessPanel() {
        initComponents();
    }
    
    public AccessPanel(MainPanel mp, TracePanel tp,int roomId,int sensId,TucsonTupleCentreId t,TucsonTupleCentreId rbac_tc,TucsonTupleCentreId casa_tc, ServiceFactory sf) {
        try {
            db = sf.getDatabaseInterface().getDatabase();
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
        this.mp = mp;
        this.tp = tp;
        this.rbac = rbac_tc;
        this.casa = casa_tc;
	this.us = sf.getUserServiceInterface();
        rId = roomId;
        sId = sensId;
        tid = t;
        initComponents();
        tUsername.grabFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tUsername = new javax.swing.JTextField();
        lbInstr1 = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();
        pwd = new javax.swing.JPasswordField();
        lbInstr0 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(538, 343));
        setMinimumSize(new java.awt.Dimension(538, 343));
        setPreferredSize(new java.awt.Dimension(538, 343));

        tUsername.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        tUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbInstr1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lbInstr1.setForeground(new java.awt.Color(1, 1, 153));
        lbInstr1.setText("and press OK in order to access the system:");

        btLogin.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btLogin.setForeground(new java.awt.Color(1, 1, 153));
        btLogin.setText("Log In");
        btLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginaccessSystem(evt);
            }
        });

        pwd.setFont(new java.awt.Font("Courier", 0, 14)); // NOI18N
        pwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbInstr0.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lbInstr0.setForeground(new java.awt.Color(1, 1, 153));
        lbInstr0.setText("Please insert USERNAME, PASSWORD and FINGERPRINT");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(88, 88, 88)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbInstr1)
                            .add(layout.createSequentialGroup()
                                .add(62, 62, 62)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(pwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 223, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(tUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 223, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(btLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 223, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(layout.createSequentialGroup()
                        .add(71, 71, 71)
                        .add(lbInstr0)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(58, 58, 58)
                .add(lbInstr0)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbInstr1)
                .add(20, 20, 20)
                .add(tUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24)
                .add(pwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 95, Short.MAX_VALUE)
                .add(btLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginaccessSystem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginaccessSystem
        String username = this.tUsername.getText();
        String passwd = String.copyValueOf(this.pwd.getPassword());
        if(Utilities.isEmpty(username) || Utilities.isEmpty(passwd)) {
            javax.swing.JOptionPane.showMessageDialog(null,"Please fill in ALL the fields!",
                    "MISSING DATA",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println("CREDENTIALS: Username="+username+", Pwd="+passwd);
        //us = new UserService();
        try {
            usr = us.getUser(db,username);
        } catch(NotFoundDbException ex) {
            ex.printStackTrace();
        } catch(ResultSetDbException rex) {
            rex.printStackTrace();
        } catch (Exception ex) {
	    Logger.getLogger(AccessPanel.class.getName()).log(Level.SEVERE, null, ex);
	}
        
        if(usr != null && usr.pwd.equals(passwd)) {// && usr.pwd.compareTo(passwd)==0) {
            System.out.println("Ok, log in!");
            // notify user access
            notifyAccess();
            mp.loadInitRolePanel(usr);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null,"WRONG CREDENTIALS! Please "+
                    "insert username and password again.",
                    "WRONG CREDENTIALS",javax.swing.JOptionPane.ERROR_MESSAGE);
            emptyAccessFields();
            return;
        }
    }//GEN-LAST:event_btLoginaccessSystem
    
    private void notifyAccess() {
        try {
            /*TucsonContext ctx = Tucson.enterDefaultContext();
                  LogicTuple rv = ctx.rdp(this.rbac, new LogicTuple("active_role", new Value(3), new Var("X")));
                    if(rv==null){
                        ctx.out(this.casa, new LogicTuple("activate_req", new Value(3), new Value("default")));
                    }
            LogicTuple checkList = ctx.rdp(tid,
                        new LogicTuple("list_checkPeople",new Value(sId), // sensor
                        new Value(usr.idUser), // person
                        new Value(rId))); // room
            // if user has not been recognize, notify his presence
            if(checkList == null)
                ctx.out(tid,new LogicTuple("detection",
                        new Value("entry"),new Value(sId), // sensor
                        new Value(usr.idUser), // person
                        new Value(rId))); // room
            else
                tp.appendText("User "+usr.username+" logged in Home Manager.");*/
            TucsonAgentId aid = new TucsonAgentId("notifyAccessAgent");
            EnhancedSynchACC acc = TucsonMetaACC.getContext(aid);
            
            LogicTuple actReq = new LogicTuple("activate_req", new Value(this.usr.idUser), new Value("default"));
            LogicTuple detection = new LogicTuple("detection",
                    new Value("entry"),
                    new Value(sId), // sensor
                    new Value(usr.idUser), // person
                    new Value(rId)  // room
            );
            
            acc.out(this.casa, actReq, null);
            acc.out(tid, detection, null);
            
            tp.appendText("User " + usr.username + " logged in Home Manager");
            acc.exit();
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void emptyAccessFields() {
        this.tUsername.setText("");
        this.pwd.setText("");
    }
    
    protected void init() {
        usr = null;
        emptyAccessFields();
        this.tUsername.grabFocus();
        if(!isVisible())
            setVisible(true);
    }
    
    protected void hidePanel() {
        if(isVisible())
            setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel lbInstr0;
    private javax.swing.JLabel lbInstr1;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
    
}
