/*
 * InfoPanel.java
 *
 * Created on 15 ottobre 2006, 18.29
 */

package it.unibo.homemanager.userinterfaces;

import it.unibo.homemanager.ServiceFactory;
import it.unibo.homemanager.dbmanagement.Database;
import it.unibo.homemanager.detection.Device;
import it.unibo.homemanager.tablemap.*;
import it.unibo.homemanager.tablemap.ServicesInterfaces.DeviceServiceInterface;
import it.unibo.homemanager.tablemap.ServicesInterfaces.RoomServiceInterface;
import it.unibo.homemanager.tablemap.ServicesInterfaces.UserServiceInterface;
import it.unibo.homemanager.util.Utilities;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  admin
 */
public class InfoPanel extends javax.swing.JPanel {
    
    private ServiceFactory sf;
    private Database database;
    
    private User usr,u = null;
    private UserServiceInterface us = null;
        
    private Device d = null;
    private DeviceServiceInterface ds = null;
    
    private Room r = null;
    private RoomServiceInterface rs = null;
    
    private MainPanel mp;
    private Vector users = null,rooms = null;//,devs=null;
    private ArrayList<Device> devs = null;
    
    /** Creates new form InfoPanel */
    public InfoPanel(MainPanel mp, ServiceFactory sf) {
        this.mp = mp;
	this.sf = sf;
	try {
	    this.database = sf.getDatabaseInterface();
	} catch (Exception ex) {
	    Logger.getLogger(InfoPanel.class.getName()).log(Level.SEVERE, null, ex);
	}
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        usersPanel = new javax.swing.JTabbedPane();
        viewRoomsPanel = new javax.swing.JPanel();
        cbRooms = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tRoomData = new javax.swing.JTextArea();
        btMenuRooms = new javax.swing.JButton();
        btLogOutRooms = new javax.swing.JButton();
        viewUsersPanel = new javax.swing.JPanel();
        cbUsers = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tUserData = new javax.swing.JTextArea();
        btMenuUsers = new javax.swing.JButton();
        btLogOutUsers = new javax.swing.JButton();
        viewDevicesPanel = new javax.swing.JPanel();
        cbDevs = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tDevData = new javax.swing.JTextArea();
        btMenuDevs = new javax.swing.JButton();
        btLogOutDevs = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 51));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(538, 343));
        setMinimumSize(new java.awt.Dimension(538, 343));
        setPreferredSize(new java.awt.Dimension(538, 343));
        usersPanel.setBackground(new java.awt.Color(204, 204, 255));
        usersPanel.setForeground(new java.awt.Color(0, 0, 102));
        usersPanel.setFont(new java.awt.Font("Courier New", 1, 12));
        viewRoomsPanel.setBackground(new java.awt.Color(204, 204, 255));
        viewRoomsPanel.setFont(new java.awt.Font("Courier New", 1, 12));
        cbRooms.setFont(new java.awt.Font("Courier New", 0, 12));
        cbRooms.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRoomsItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Choose Room you want to know about:");

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Room Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 12), new java.awt.Color(0, 0, 51)));
        tRoomData.setBackground(new java.awt.Color(204, 204, 255));
        tRoomData.setColumns(20);
        tRoomData.setEditable(false);
        tRoomData.setFont(new java.awt.Font("Courier New", 1, 13));
        tRoomData.setForeground(new java.awt.Color(0, 0, 204));
        tRoomData.setLineWrap(true);
        tRoomData.setRows(5);
        tRoomData.setWrapStyleWord(true);
        tRoomData.setBorder(null);
        tRoomData.setMargin(new java.awt.Insets(9, 3, 3, 3));
        jScrollPane3.setViewportView(tRoomData);

        btMenuRooms.setFont(new java.awt.Font("Courier New", 1, 12));
        btMenuRooms.setForeground(new java.awt.Color(102, 0, 102));
        btMenuRooms.setText("MENU");
        btMenuRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuRoomsActionPerformed(evt);
            }
        });

        btLogOutRooms.setFont(new java.awt.Font("Courier New", 1, 12));
        btLogOutRooms.setForeground(new java.awt.Color(102, 0, 102));
        btLogOutRooms.setText("LOG OUT");
        btLogOutRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogOutRoomsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout viewRoomsPanelLayout = new org.jdesktop.layout.GroupLayout(viewRoomsPanel);
        viewRoomsPanel.setLayout(viewRoomsPanelLayout);
        viewRoomsPanelLayout.setHorizontalGroup(
            viewRoomsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewRoomsPanelLayout.createSequentialGroup()
                .add(viewRoomsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, viewRoomsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
                    .add(viewRoomsPanelLayout.createSequentialGroup()
                        .add(viewRoomsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(viewRoomsPanelLayout.createSequentialGroup()
                                .add(107, 107, 107)
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(28, 28, 28))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewRoomsPanelLayout.createSequentialGroup()
                                .add(335, 335, 335)
                                .add(btMenuRooms, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .add(14, 14, 14)))
                        .add(btLogOutRooms)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewRoomsPanelLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .add(cbRooms, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 249, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(137, 137, 137))
        );
        viewRoomsPanelLayout.setVerticalGroup(
            viewRoomsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(viewRoomsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(viewRoomsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btLogOutRooms)
                    .add(btMenuRooms))
                .add(15, 15, 15)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cbRooms, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );
        usersPanel.addTab("View Rooms", viewRoomsPanel);

        viewUsersPanel.setBackground(new java.awt.Color(204, 204, 255));
        viewUsersPanel.setFont(new java.awt.Font("Courier New", 1, 12));
        cbUsers.setFont(new java.awt.Font("Courier New", 0, 12));
        cbUsers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUsersItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose User you want to know about:");

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "User Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 12), new java.awt.Color(0, 0, 51)));
        tUserData.setBackground(new java.awt.Color(204, 204, 255));
        tUserData.setColumns(20);
        tUserData.setEditable(false);
        tUserData.setFont(new java.awt.Font("Courier New", 1, 13));
        tUserData.setForeground(new java.awt.Color(0, 0, 204));
        tUserData.setLineWrap(true);
        tUserData.setRows(5);
        tUserData.setWrapStyleWord(true);
        tUserData.setBorder(null);
        tUserData.setMargin(new java.awt.Insets(9, 3, 3, 3));
        jScrollPane1.setViewportView(tUserData);

        btMenuUsers.setFont(new java.awt.Font("Courier New", 1, 12));
        btMenuUsers.setForeground(new java.awt.Color(102, 0, 102));
        btMenuUsers.setText("MENU");
        btMenuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuUsersActionPerformed(evt);
            }
        });

        btLogOutUsers.setFont(new java.awt.Font("Courier New", 1, 12));
        btLogOutUsers.setForeground(new java.awt.Color(102, 0, 102));
        btLogOutUsers.setText("LOG OUT");
        btLogOutUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogOutUsersActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout viewUsersPanelLayout = new org.jdesktop.layout.GroupLayout(viewUsersPanel);
        viewUsersPanel.setLayout(viewUsersPanelLayout);
        viewUsersPanelLayout.setHorizontalGroup(
            viewUsersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewUsersPanelLayout.createSequentialGroup()
                .add(viewUsersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, viewUsersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, viewUsersPanelLayout.createSequentialGroup()
                        .add(136, 136, 136)
                        .add(cbUsers, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(viewUsersPanelLayout.createSequentialGroup()
                        .add(viewUsersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(viewUsersPanelLayout.createSequentialGroup()
                                .add(107, 107, 107)
                                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(28, 28, 28))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewUsersPanelLayout.createSequentialGroup()
                                .add(335, 335, 335)
                                .add(btMenuUsers, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .add(14, 14, 14)))
                        .add(btLogOutUsers)))
                .addContainerGap())
        );
        viewUsersPanelLayout.setVerticalGroup(
            viewUsersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(viewUsersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(viewUsersPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btLogOutUsers)
                    .add(btMenuUsers))
                .add(15, 15, 15)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(cbUsers, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 19, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );
        usersPanel.addTab("View Users", viewUsersPanel);

        viewDevicesPanel.setBackground(new java.awt.Color(204, 204, 255));
        viewDevicesPanel.setFont(new java.awt.Font("Courier New", 1, 12));
        cbDevs.setFont(new java.awt.Font("Courier New", 0, 12));
        cbDevs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDevsItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choose Device you want to know about:");

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Device Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 12), new java.awt.Color(0, 0, 51)));
        tDevData.setBackground(new java.awt.Color(204, 204, 255));
        tDevData.setColumns(20);
        tDevData.setEditable(false);
        tDevData.setFont(new java.awt.Font("Courier New", 1, 13));
        tDevData.setForeground(new java.awt.Color(0, 0, 204));
        tDevData.setLineWrap(true);
        tDevData.setRows(5);
        tDevData.setWrapStyleWord(true);
        tDevData.setBorder(null);
        tDevData.setMargin(new java.awt.Insets(9, 3, 3, 3));
        jScrollPane2.setViewportView(tDevData);

        btMenuDevs.setFont(new java.awt.Font("Courier New", 1, 12));
        btMenuDevs.setForeground(new java.awt.Color(102, 0, 102));
        btMenuDevs.setText("MENU");
        btMenuDevs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuDevsActionPerformed(evt);
            }
        });

        btLogOutDevs.setFont(new java.awt.Font("Courier New", 1, 12));
        btLogOutDevs.setForeground(new java.awt.Color(102, 0, 102));
        btLogOutDevs.setText("LOG OUT");
        btLogOutDevs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogOutDevsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout viewDevicesPanelLayout = new org.jdesktop.layout.GroupLayout(viewDevicesPanel);
        viewDevicesPanel.setLayout(viewDevicesPanelLayout);
        viewDevicesPanelLayout.setHorizontalGroup(
            viewDevicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewDevicesPanelLayout.createSequentialGroup()
                .add(viewDevicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, viewDevicesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
                    .add(viewDevicesPanelLayout.createSequentialGroup()
                        .add(viewDevicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(viewDevicesPanelLayout.createSequentialGroup()
                                .add(107, 107, 107)
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(28, 28, 28))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, viewDevicesPanelLayout.createSequentialGroup()
                                .add(viewDevicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, viewDevicesPanelLayout.createSequentialGroup()
                                        .add(85, 85, 85)
                                        .add(cbDevs, 0, 337, Short.MAX_VALUE))
                                    .add(viewDevicesPanelLayout.createSequentialGroup()
                                        .add(335, 335, 335)
                                        .add(btMenuDevs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                                .add(14, 14, 14)))
                        .add(btLogOutDevs)))
                .addContainerGap())
        );
        viewDevicesPanelLayout.setVerticalGroup(
            viewDevicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(viewDevicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(viewDevicesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btLogOutDevs)
                    .add(btMenuDevs))
                .add(15, 15, 15)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(cbDevs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 19, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );
        usersPanel.addTab("View Devices", viewDevicesPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(usersPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(usersPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btLogOutRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogOutRoomsActionPerformed
        mp.logOut(evt);
    }//GEN-LAST:event_btLogOutRoomsActionPerformed

    private void btMenuRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuRoomsActionPerformed
        mp.loadInitRolePanel(u);
    }//GEN-LAST:event_btMenuRoomsActionPerformed

    private void cbRoomsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRoomsItemStateChanged
        if(cbRooms.getSelectedItem() != null) {
            try {
                r = rs.getRoomByName(database.getDatabase(),
                        cbRooms.getSelectedItem().toString());
            }
            catch(Exception ex) {
                ex.printStackTrace();
            }
            tRoomData.setText(r.toString());
        }
    }//GEN-LAST:event_cbRoomsItemStateChanged

    private void btLogOutDevsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogOutDevsActionPerformed
        mp.logOut(evt);
    }//GEN-LAST:event_btLogOutDevsActionPerformed

    private void btMenuDevsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuDevsActionPerformed
        mp.loadInitRolePanel(u);
    }//GEN-LAST:event_btMenuDevsActionPerformed

    private void cbDevsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDevsItemStateChanged
        if(cbDevs.getSelectedItem() != null) {
            try {
                String str = cbDevs.getSelectedItem().toString();
                StringTokenizer tokenizer = new StringTokenizer(str,",");
                String devName = tokenizer.nextToken().trim();
                String rName = tokenizer.nextToken().trim();
                Room rm = Utilities.findRoomByName(rs.getRooms(database.getDatabase()),rName);
                d = ds.getDevice(database.getDatabase(),devName.substring(1, devName.length()-1),rm.idRoom);
            }
            catch(Exception ex) {
                ex.printStackTrace();
            }
            tDevData.setText(d.toString());
        }
    }//GEN-LAST:event_cbDevsItemStateChanged

    private void btLogOutUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogOutUsersActionPerformed
        mp.logOut(evt);
    }//GEN-LAST:event_btLogOutUsersActionPerformed

    private void btMenuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuUsersActionPerformed
        mp.loadInitRolePanel(u);
    }//GEN-LAST:event_btMenuUsersActionPerformed

    private void cbUsersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUsersItemStateChanged
        if(cbUsers.getSelectedItem() != null) {
            try {
                usr = us.getUser(database.getDatabase(),cbUsers.getSelectedItem().toString());
            }
            catch(Exception ex) {
                ex.printStackTrace();
            }
            tUserData.setText(usr.toString());
        }
    }//GEN-LAST:event_cbUsersItemStateChanged
    
    protected void init(User usr) {
        cbUsers.removeAllItems();
        cbDevs.removeAllItems();
        cbRooms.removeAllItems();
        
        u = usr;
        // load room data
        try {
            rs = sf.getRoomServiceInterface();
            rooms = rs.getRooms(database.getDatabase());
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        for(int i=0;i<rooms.size();i++) {
            String rName = ((Room) rooms.elementAt(i)).name;
            cbRooms.addItem(rName);
        }
        cbRooms.setSelectedItem(0);
        // load device data
        try {
            ds = sf.getDeviceServiceInterface();
            
            devs = ds.getDevices(database.getDatabase());
            for(int i=0;i<devs.size();i++) {
                Device dv = devs.get(i);//(Device) devs.elementAt(i);
                Room rm = rs.getRoomById(database.getDatabase(),dv.getDeviceId());
                String dName = dv.getDeviceName()+", "+rm.name;
                cbDevs.addItem(dName);
            }
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        cbDevs.setSelectedItem(0);
        // load user data
        try {
            us = sf.getUserServiceInterface();
            users = us.getUsers(database.getDatabase());
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        for(int i=0;i<users.size();i++) {
            String uName = ((User) users.elementAt(i)).username;
            cbUsers.addItem(uName);
        }
        cbUsers.setSelectedItem(0);
        //
        if(!isVisible())
            setVisible(true);
    }
    
    protected void hidePanel() {
        if(isVisible())
            setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogOutDevs;
    private javax.swing.JButton btLogOutRooms;
    private javax.swing.JButton btLogOutUsers;
    private javax.swing.JButton btMenuDevs;
    private javax.swing.JButton btMenuRooms;
    private javax.swing.JButton btMenuUsers;
    private javax.swing.JComboBox cbDevs;
    private javax.swing.JComboBox cbRooms;
    private javax.swing.JComboBox cbUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea tDevData;
    private javax.swing.JTextArea tRoomData;
    private javax.swing.JTextArea tUserData;
    private javax.swing.JTabbedPane usersPanel;
    private javax.swing.JPanel viewDevicesPanel;
    private javax.swing.JPanel viewRoomsPanel;
    private javax.swing.JPanel viewUsersPanel;
    // End of variables declaration//GEN-END:variables
    
}
