/*
 * InitOrdinaryPanel.java
 *
 * Created on 1 novembre 2006, 17.34
 */

package it.unibo.homemanager.userinterfaces;

import alice.tucson.api.*;
import alice.logictuple.*;
import it.unibo.homemanager.tablemap.User;
import it.unibo.homemanager.util.Utilities;

/**
 *
 * @author  admin
 */
public class InitOrdinaryPanel extends javax.swing.JPanel {
    
    private MainPanel mp;
    
    private String hi = "",role = "";
    private User usr = null;
    private TucsonTupleCentreId casa, rbac;
    
    /** Creates new form InitOrdinaryPanel */
    public InitOrdinaryPanel(MainPanel mp, TucsonTupleCentreId casa_tc, TucsonTupleCentreId rbac_tc) {
        this.mp = mp;
        this.casa = casa_tc;
        this.rbac = rbac_tc;
        initComponents();
    }
    
    protected void init(User u) {
        usr = u;
        hi = "Hi "+u.firstname+"!";
        findRole();
        lHi.setText(hi); // change label with name
        lRole.setText(role); // change label with role
        //
        if(!isVisible())
            setVisible(true);
    }
    
    private void findRole() {
        try{
            TucsonAgentId agent = new TucsonAgentId("findRoleAgent");
            EnhancedSynchACC acc = TucsonMetaACC.getContext(agent);
            
            //LogicTuple activateRequestTemplate = new LogicTuple("activate_req", new Value(usr.idUser), new Value("default"));
            LogicTuple defaultActivateTemplate = new LogicTuple("default_activate", new Value(usr.idUser), new Var("Y"));
            
            //acc.out(this.casa, activateRequestTemplate, null);
            ITucsonOperation op_rdp = acc.rdp(this.rbac, defaultActivateTemplate, null);
            LogicTuple lt = op_rdp.getLogicTupleResult();
            role = "Role: "+lt.getArg(1).getName();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    protected void hidePanel() {
        if(isVisible())
            setVisible(false);
    }
    
    protected String getFirstname() {
        return usr.firstname;
    }
    
    protected String getRole() {
        //return Utilities.writeRole(usr.role.charAt(1));
	return Utilities.writeRole(usr.getRoleChar());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btViewInfo = new javax.swing.JButton();
        btViewPlan = new javax.swing.JButton();
        btViewPolicy = new javax.swing.JButton();
        btManCmd = new javax.swing.JButton();
        btLogOut = new javax.swing.JButton();
        lHi = new javax.swing.JLabel();
        lRole = new javax.swing.JLabel();
        btProfile = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(538, 343));
        setMinimumSize(new java.awt.Dimension(538, 343));
        setPreferredSize(new java.awt.Dimension(538, 343));

        btViewInfo.setFont(new java.awt.Font("Courier New", 1, 14));
        btViewInfo.setForeground(new java.awt.Color(102, 0, 102));
        btViewInfo.setText("View Info");
        btViewInfo.setMaximumSize(new java.awt.Dimension(155, 27));
        btViewInfo.setMinimumSize(new java.awt.Dimension(155, 27));
        btViewInfo.setPreferredSize(new java.awt.Dimension(155, 27));
        btViewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewInfoActionPerformed(evt);
            }
        });

        btViewPlan.setFont(new java.awt.Font("Courier New", 1, 14));
        btViewPlan.setForeground(new java.awt.Color(102, 0, 102));
        btViewPlan.setText("View Plan");
        btViewPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewPlanActionPerformed(evt);
            }
        });

        btViewPolicy.setFont(new java.awt.Font("Courier New", 1, 14));
        btViewPolicy.setForeground(new java.awt.Color(102, 0, 102));
        btViewPolicy.setText("View Policy");
        btViewPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewPolicyActionPerformed(evt);
            }
        });

        btManCmd.setFont(new java.awt.Font("Courier New", 1, 14));
        btManCmd.setForeground(new java.awt.Color(102, 0, 102));
        btManCmd.setText("Issue Command");
        btManCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManCmdissueManCmd(evt);
            }
        });

        btLogOut.setFont(new java.awt.Font("Courier New", 1, 14));
        btLogOut.setForeground(new java.awt.Color(102, 0, 102));
        btLogOut.setText("LOG OUT");
        btLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogOutlogOut(evt);
            }
        });

        lHi.setFont(new java.awt.Font("Courier New", 1, 18));
        lHi.setForeground(new java.awt.Color(153, 0, 153));
        lHi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lHi.setInheritsPopupMenu(false);

        lRole.setFont(new java.awt.Font("Courier New", 1, 15));
        lRole.setForeground(new java.awt.Color(153, 0, 153));
        lRole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lRole.setInheritsPopupMenu(false);

        btProfile.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btProfile.setForeground(new java.awt.Color(102, 0, 102));
        btProfile.setText("Manage Profile");
        btProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProfileActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 51, 51));
        jToggleButton1.setText("RBAC");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lRole, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, lHi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 90, Short.MAX_VALUE)
                .add(btLogOut)
                .add(38, 38, 38))
            .add(layout.createSequentialGroup()
                .add(182, 182, 182)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btManCmd, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btViewPolicy, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .add(btViewPlan, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .add(btViewInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jToggleButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .add(btProfile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .add(191, 191, 191))
        );

        layout.linkSize(new java.awt.Component[] {btManCmd, btProfile, btViewInfo, btViewPlan, btViewPolicy, jToggleButton1}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lHi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .add(btLogOut))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lRole, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btViewInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btViewPlan)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btViewPolicy)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btManCmd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btProfile)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jToggleButton1)
                .add(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProfileActionPerformed
        mp.loadManageProfilePanel();
    }//GEN-LAST:event_btProfileActionPerformed

    private void btLogOutlogOut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogOutlogOut
        mp.logOut(evt);
    }//GEN-LAST:event_btLogOutlogOut

    private void btManCmdissueManCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManCmdissueManCmd
        mp.loadIssueCmdPanel();
    }//GEN-LAST:event_btManCmdissueManCmd

    private void btViewPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewPolicyActionPerformed
        mp.loadViewPolicyPanel();
    }//GEN-LAST:event_btViewPolicyActionPerformed

    private void btViewPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewPlanActionPerformed
        mp.loadViewPlanPanel();
    }//GEN-LAST:event_btViewPlanActionPerformed

    private void btViewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewInfoActionPerformed
        mp.loadInfoPanel();
    }//GEN-LAST:event_btViewInfoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        mp.loadViewUsersRBACPanel();
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogOut;
    private javax.swing.JButton btManCmd;
    private javax.swing.JButton btProfile;
    private javax.swing.JButton btViewInfo;
    private javax.swing.JButton btViewPlan;
    private javax.swing.JButton btViewPolicy;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lHi;
    private javax.swing.JLabel lRole;
    // End of variables declaration//GEN-END:variables
    
}
