/*
 * InitAdminPanel.java
 *
 * Created on 15 ottobre 2006, 12.36
 */

package it.unibo.homemanager.userinterfaces;

import it.unibo.homemanager.tablemap.User;
import it.unibo.homemanager.util.Utilities;

import java.util.List;

import alice.tucson.api.*;
import alice.logictuple.*;

import java.util.ArrayList;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.Dimension;

/**
 *
 * @author  admin
 */
public class InitAdminPanel extends javax.swing.JPanel {
    
    private MainPanel mp;
    //private TupleCentreId tid;
    private Vector tid;
    private String hi = "",role = "";
    private User usr;

    private TucsonTupleCentreId casa, rbac;
    /** Creates new form InitAdminPanel */
    public InitAdminPanel(MainPanel mp,Vector t, TucsonTupleCentreId casa_tc, TucsonTupleCentreId rbac_tc) {
        initComponents();
        this.mp = mp;
        this.casa = casa_tc;
        this.rbac = rbac_tc;
        tid = t;
    }
    
    protected void init(User u) {
        usr = u;
        hi = "Hi "+u.firstname+"!";
        findRole();
        lHi.setText(hi); // change label with name
        lRole.setText(role); // change label with role
        // check if there have been visitors.
        checkVisitors();
        if(!isVisible())
            setVisible(true);
    }
    
    private void findRole() {
        try{
            TucsonAgentId agent = new TucsonAgentId("findRoleAgent");
            EnhancedSynchACC acc = TucsonMetaACC.getContext(agent);
            
            //LogicTuple activateRequestTemplate = new LogicTuple("activate_req", new Value(usr.idUser), new Value("default"));
            LogicTuple defaultActivateTemplate = new LogicTuple("default_activate", new Value(usr.idUser), new Var("Y"));
            
            //acc.out(this.casa, activateRequestTemplate, null);
            ITucsonOperation op_rdp = acc.rdp(this.rbac, defaultActivateTemplate, null);
            LogicTuple lt = op_rdp.getLogicTupleResult();
            role = "Role: "+lt.getArg(1).getName();
            acc.exit();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void checkVisitors() {
        try {
            TucsonAgentId agent = new TucsonAgentId("checkVisitorAgent");
            EnhancedSynchACC acc = TucsonMetaACC.getContext(agent);
            
            LogicTuple visitorTemplate = new LogicTuple("visitor", new Var("X"));
            List l = new ArrayList();

            for(int i=0;i<this.tid.size();i++) {
                ITucsonOperation op_inAll = acc.inAll((TucsonTupleCentreId)tid.elementAt(i), visitorTemplate, Long.MAX_VALUE);
                l.addAll(op_inAll.getLogicTupleListResult());
            }
            
            if(l.size() > 0)
                javax.swing.JOptionPane.showMessageDialog(null,
                        l.size()+" VISITOR"+(l.size()>1?"S":"")+" DETECTED.",
                        "INFORMATION",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            acc.exit();
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
    }
    
    protected void hidePanel() {
        if(isVisible())
            setVisible(false);
    }
    
    protected String getFirstname() {
        return usr.firstname;
    }
    
    protected String getRole() {
        //return Utilities.writeRole(usr.role.charAt(1));
	return Utilities.writeRole(usr.getRoleChar());
    }
    
    protected User getUser() {
        return usr;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lHi = new javax.swing.JLabel();
        btProfile = new javax.swing.JButton();
        btUsers = new javax.swing.JButton();
        btPolicy = new javax.swing.JButton();
        btVisitors = new javax.swing.JButton();
        btViewInfo = new javax.swing.JButton();
        btViewPlan = new javax.swing.JButton();
        btViewPolicy = new javax.swing.JButton();
        btLogOut = new javax.swing.JButton();
        lRole = new javax.swing.JLabel();
        btManCmd = new javax.swing.JButton();
        btManRBAC = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(538, 343));
        setMinimumSize(new java.awt.Dimension(538, 343));
        setPreferredSize(new java.awt.Dimension(538, 343));

        lHi.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lHi.setForeground(new java.awt.Color(153, 0, 153));
        lHi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lHi.setInheritsPopupMenu(false);

        btProfile.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btProfile.setForeground(new java.awt.Color(102, 0, 102));
        btProfile.setText("Manage Profile");
        btProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProfileActionPerformed(evt);
            }
        });

        btUsers.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btUsers.setForeground(new java.awt.Color(102, 0, 102));
        btUsers.setText("Manage Users");
        btUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsersActionPerformed(evt);
            }
        });

        btPolicy.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btPolicy.setForeground(new java.awt.Color(102, 0, 102));
        btPolicy.setText("Manage Policy");
        btPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPolicyActionPerformed(evt);
            }
        });

        btVisitors.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btVisitors.setForeground(new java.awt.Color(102, 0, 102));
        btVisitors.setText("Manage Visitors");
        btVisitors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisitorsActionPerformed(evt);
            }
        });

        btViewInfo.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btViewInfo.setForeground(new java.awt.Color(102, 0, 102));
        btViewInfo.setText("View Info");
        btViewInfo.setMaximumSize(new java.awt.Dimension(155, 27));
        btViewInfo.setMinimumSize(new java.awt.Dimension(155, 27));
        btViewInfo.setPreferredSize(new java.awt.Dimension(155, 27));
        btViewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewInfoActionPerformed(evt);
            }
        });

        btViewPlan.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btViewPlan.setForeground(new java.awt.Color(102, 0, 102));
        btViewPlan.setText("View Plan");
        btViewPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewPlanActionPerformed(evt);
            }
        });

        btViewPolicy.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btViewPolicy.setForeground(new java.awt.Color(102, 0, 102));
        btViewPolicy.setText("View Policy");
        btViewPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewPolicyActionPerformed(evt);
            }
        });

        btLogOut.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btLogOut.setForeground(new java.awt.Color(102, 0, 102));
        btLogOut.setText("LOG OUT");
        btLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut(evt);
            }
        });

        lRole.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        lRole.setForeground(new java.awt.Color(153, 0, 153));
        lRole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lRole.setInheritsPopupMenu(false);

        btManCmd.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btManCmd.setForeground(new java.awt.Color(102, 0, 102));
        btManCmd.setText("Issue Command");
        btManCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManCmdissueManCmd(evt);
            }
        });

        btManRBAC.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btManRBAC.setForeground(new java.awt.Color(255, 51, 51));
        btManRBAC.setText("Manage RBAC");
        btManRBAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManRBACActionPerformed(evt);
            }
        });
        
        JButton AgentButton = new JButton("Agenti");
        AgentButton.setMaximumSize(new Dimension(33, 9));
        AgentButton.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        AgentButton.setForeground(new java.awt.Color(102, 0, 102));
        AgentButton.setText("Butlers");
        AgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(89)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        					.addComponent(lHi, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE)
        					.addComponent(lRole, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(btProfile, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btPolicy, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btUsers, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btVisitors, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(AgentButton, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
        					.addComponent(btLogOut))
        				.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(btViewInfo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btManCmd, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btViewPolicy, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btViewPlan, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(btManRBAC, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        			.addGap(101))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(29)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lHi, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btLogOut))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(lRole, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btManRBAC)
        				.addComponent(AgentButton, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btViewInfo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btVisitors))
        			.addGap(19)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btViewPlan)
        				.addComponent(btUsers))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(btViewPolicy)
        					.addComponent(btPolicy))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(47)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(btProfile)
        						.addComponent(btManCmd, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))))
        			.addGap(33))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    
	private void AgentButtonActionPerformed(ActionEvent evt) {
		mp.loadButlerPanel();
	}
    
    
    private void btUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsersActionPerformed
        mp.loadManageUsersPanel();
    }//GEN-LAST:event_btUsersActionPerformed

    private void btProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProfileActionPerformed
        mp.loadManageProfilePanel();
    }//GEN-LAST:event_btProfileActionPerformed

    private void btViewPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewPlanActionPerformed
        mp.loadViewPlanPanel();
    }//GEN-LAST:event_btViewPlanActionPerformed

    private void btVisitorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisitorsActionPerformed
        mp.loadVisitorsPanel();
    }//GEN-LAST:event_btVisitorsActionPerformed

    private void btPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPolicyActionPerformed
        mp.loadPolicyPanel();
    }//GEN-LAST:event_btPolicyActionPerformed

    private void btViewPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewPolicyActionPerformed
        mp.loadViewPolicyPanel();
    }//GEN-LAST:event_btViewPolicyActionPerformed

    private void btViewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewInfoActionPerformed
        mp.loadInfoPanel();
    }//GEN-LAST:event_btViewInfoActionPerformed

    private void btManCmdissueManCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManCmdissueManCmd
        mp.loadIssueCmdPanel();
    }//GEN-LAST:event_btManCmdissueManCmd

    private void logOut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut
        mp.logOut(evt);
    }//GEN-LAST:event_logOut

    private void btManRBACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManRBACActionPerformed
        // TODO add your handling code here:
        mp.loadManRBACPanel();
    }//GEN-LAST:event_btManRBACActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogOut;
    private javax.swing.JButton btManCmd;
    private javax.swing.JButton btManRBAC;
    private javax.swing.JButton btPolicy;
    private javax.swing.JButton btProfile;
    private javax.swing.JButton btUsers;
    private javax.swing.JButton btViewInfo;
    private javax.swing.JButton btViewPlan;
    private javax.swing.JButton btViewPolicy;
    private javax.swing.JButton btVisitors;
    private javax.swing.JLabel lHi;
    private javax.swing.JLabel lRole;
}
