/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManRoles.java
 *
 * Created on 19-set-2009, 10.26.33
 */

package it.unibo.homemanager.userinterfaces;


import alice.tucson.api.*;
import alice.logictuple.*;
import alice.tucson.api.exceptions.TucsonInvalidAgentIdException;
import it.unibo.homemanager.tablemap.User;
import it.unibo.homemanager.util.Utilities;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class ManRoles extends javax.swing.JPanel {

    private MainPanel mp;
    private TucsonTupleCentreId rbac;
    private RBACManager rbac_man;
    private User us;
    private String role_to_modify;
    
    private TucsonAgentId agent;
    
    /** Creates new form ManRoles */
    public ManRoles(MainPanel mainp, TucsonTupleCentreId tc, RBACManager rm) {
        this.mp = mainp;
        this.rbac = tc;
        this.rbac_man = rm;
        try {
            agent = new TucsonAgentId("manageRolesAgent");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        initComponents();
    }

    public void init(User u){
        this.us = u;
        fillListRoles();
        if(!isVisible())
            setVisible(true);
    }


    private void fillListRoles(){
        List<LogicTuple> roles;
        Vector rolesVector = new Vector();
        
        try {
            EnhancedSynchACC acc = TucsonMetaACC.getContext(agent);
            
            ITucsonOperation op_rdAll = acc.rdAll(rbac, new LogicTuple("role", new Var("X")), null);
                //LogicTuple rl = ctx.inp(this.rbac, new LogicTuple("rd_all", new Value("role", new Var("X")), new Var("Y")));
                //System.err.println("roles: "+rl);
                //roles = rl.getArg(1).toList();
            roles = op_rdAll.getLogicTupleListResult();
            System.err.println("roles: " + roles);

            //    LogicTuple rol;
            for(int i=0;i<roles.size();i++)
                rolesVector.add(roles.get(i).getArg(0).getName());
                //{
                    //rol = LogicTuple.parse(roles.get(i).toString());
                    //ro.add(rol.getArg(0).getName());
                //}
            this.jList_Roles.setListData(rolesVector);
            acc.exit();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void save_new_role(String new_role){
        try {
            //String role = "+new_role+"'";
            EnhancedSynchACC acc = TucsonMetaACC.getContext(agent);
            LogicTuple roleTemplate = new LogicTuple("role", new Value(new_role));
            //Utilities.insertTupleInto(rbac, roleTemplate);
            acc.out(rbac, roleTemplate, null);
            acc.exit();
            fillListRoles();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void delete_role(String del_role){
        //String role = "'"+del_role+"'";
        try{
            EnhancedSynchACC acc = TucsonMetaACC.getContext(agent);
            acc.in(this.rbac, new LogicTuple("role", new Value(del_role)), null);
            acc.exit();
            fillListRoles();
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }

    private void modify_role(String role_to_modify, String new_role){
        try{
            EnhancedSynchACC acc = TucsonMetaACC.getContext(agent);
            System.err.println("Ruolo da modificare: "+role_to_modify+" - Ruolo Modificato: "+new_role);
            LogicTuple modifyRoleTemplate = new LogicTuple("modify_role", new Value(role_to_modify), new Value(new_role));
            acc.out(rbac, modifyRoleTemplate, null);
            //Utilities.insertTupleInto(rbac, modifyRoleTemplate);
            acc.exit();
            fillListRoles();
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Roles = new javax.swing.JTextField();
        jTextField_Role = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Roles = new javax.swing.JList();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(538, 343));

        jTextField_Role.setText("Type here new role name");
        jTextField_Role.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_RoleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_RoleFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel1.setText("Role Name:");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel2.setText("Roles:");

        jButton1.setFont(new java.awt.Font("Courier New", 1, 14));
        jButton1.setText("Modify");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Courier New", 1, 14));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Courier New", 1, 14));
        jButton3.setText("Save New Role");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Courier New", 1, 14));
        jButton4.setText("RBAC MENU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Courier New", 1, 14));
        jButton5.setText("MENU");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Courier New", 1, 14));
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jList_Roles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_Roles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_Roles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_RolesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_Roles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jTextField_Role, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton4, jButton5, jButton6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton5)
                        .addComponent(jButton4))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Role, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!this.jTextField_Role.getText().equals("Type here new role name") || !this.jTextField_Role.getText().equals(""))
            modify_role(this.role_to_modify, this.jTextField_Role.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!this.jTextField_Role.getText().equals("Type here new role name") || !this.jTextField_Role.getText().equals(""))
        delete_role(this.jTextField_Role.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.mp.logOut(evt);
}//GEN-LAST:event_jButton6ActionPerformed

    private void jList_RolesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_RolesValueChanged
        // TODO add your handling code here:
        this.role_to_modify = (String)this.jList_Roles.getSelectedValue();
        this.jTextField_Role.setText(role_to_modify);
    }//GEN-LAST:event_jList_RolesValueChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.mp.loadInitRolePanel(this.us);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.mp.loadManRBACPanel();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField_RoleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_RoleFocusGained
        // TODO add your handling code here:
        this.jTextField_Role.setText("");
    }//GEN-LAST:event_jTextField_RoleFocusGained

    private void jTextField_RoleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_RoleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RoleFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!this.jTextField_Role.getText().equals("Type here new role name") || !this.jTextField_Role.getText().equals(""))
        save_new_role(this.jTextField_Role.getText());
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList_Roles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Role;
    private javax.swing.JTextField jTextField_Roles;
    // End of variables declaration//GEN-END:variables
    
    protected void hidePanel() {
        if(isVisible())
            setVisible(false);
    }
}
