/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibo.homemanager.userinterfaces;

import alice.tucson.api.TucsonTupleCentreId;
import it.unibo.homemanager.agents.TucsonShopperAgent;
import it.unibo.homemanager.tablemap.User;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vincenzo
 */
public class ViewShopperAgentPanel extends javax.swing.JPanel {

    
    private ViewManageAgentPanel butlerPanel;
    private TracePanel tp;
    private TucsonShopperAgent shopperAgent;
    private FormYourOrder viewYourOrder;
    private int threshold;
   /**
     * Creates new form ViewShopperAgentPanel
     */

    public ViewShopperAgentPanel(ViewManageAgentPanel mAPanel, TucsonShopperAgent shopperAgent, TracePanel tp) {
        this.butlerPanel=mAPanel;
        this.shopperAgent=shopperAgent;
        this.tp=tp;
        viewYourOrder=new FormYourOrder();
        viewYourOrder.setVisible(false);
        initComponents();
    }
    
     public void hidePanel() {
        if(isVisible())
            setVisible(false);
    }
     
    public void init() {
        fillList();
        loadThreshold();
        if(!isVisible())
            setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        listScarcity = new java.awt.List();
        menuButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        thresholdTextField = new javax.swing.JTextField();
        plusThresholdButton = new javax.swing.JButton();
        lessThresholdButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        yourOrderButton = new javax.swing.JButton();
        saveThresholdButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(538, 343));
        setMinimumSize(new java.awt.Dimension(538, 343));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrello.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("Shopper Agent");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Products to buy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listScarcity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listScarcity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuButton.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        thresholdTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        thresholdTextField.setText("10");

        plusThresholdButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        plusThresholdButton.setText("+");
        plusThresholdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusThresholdButtonActionPerformed(evt);
            }
        });

        lessThresholdButton.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lessThresholdButton.setText("-");
        lessThresholdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessThresholdButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Threshold value to buy shopping");

        yourOrderButton.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        yourOrderButton.setText("Your Orders");
        yourOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourOrderButtonActionPerformed(evt);
            }
        });

        saveThresholdButton.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        saveThresholdButton.setText("Save Threshold");
        saveThresholdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveThresholdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(107, 107, 107))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plusThresholdButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lessThresholdButton)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(saveThresholdButton))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(yourOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusThresholdButton)
                    .addComponent(lessThresholdButton)
                    .addComponent(saveThresholdButton))
                .addGap(22, 22, 22)
                .addComponent(yourOrderButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton)
                    .addComponent(backButton))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        this.hidePanel();
        butlerPanel.menu();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.hidePanel();
        butlerPanel.showPanel();
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveThresholdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveThresholdButtonActionPerformed
       int choice = JOptionPane.showConfirmDialog(null,
                "Do you really want to insert this threshold value?",
                "INSERT THRESHOLD CHECK", JOptionPane.OK_CANCEL_OPTION);
        if (choice == JOptionPane.OK_OPTION) {
            int threshold=Integer.parseInt(this.thresholdTextField.getText());
            this.shopperAgent.insert(threshold);
            return;
        } else {
            JOptionPane.showMessageDialog(null,
                    "Threshold not added,try again.",
                    "ACTION NOT SUCCEEDE", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_saveThresholdButtonActionPerformed

    private void yourOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourOrderButtonActionPerformed
        ArrayList<String> orders=shopperAgent.getListOrderToString();
        if(orders.size()!=0){
            viewYourOrder.refreshList(orders);
            //viewYourOrder.fiillTextArea(lista);
            viewYourOrder.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "There are no orders, empty cart.",
                    "EMPTY CART", JOptionPane.NO_OPTION);
        }    
    }//GEN-LAST:event_yourOrderButtonActionPerformed

    private void plusThresholdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusThresholdButtonActionPerformed
        int num_threshold=Integer.parseInt(this.thresholdTextField.getText());
        num_threshold++;
        this.thresholdTextField.setText(String.valueOf(num_threshold));
    }//GEN-LAST:event_plusThresholdButtonActionPerformed

    private void lessThresholdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessThresholdButtonActionPerformed
        int num_threshold=Integer.parseInt(this.thresholdTextField.getText());
        if(num_threshold>2){
            num_threshold--;
            this.thresholdTextField.setText(String.valueOf(num_threshold));
        }else{
            JOptionPane.showMessageDialog(null,
                    "Threshold too low, action not permitted",
                    "ACTION NOT PERMITTED", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_lessThresholdButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lessThresholdButton;
    public java.awt.List listScarcity;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton plusThresholdButton;
    private javax.swing.JButton saveThresholdButton;
    private javax.swing.JTextField thresholdTextField;
    private javax.swing.JButton yourOrderButton;
    // End of variables declaration//GEN-END:variables

    public void fillList() {
        listScarcity.removeAll();
        ArrayList<String> product_list=new ArrayList<String>();
        try {
            product_list=shopperAgent.getListProduct();
        } catch (Exception ex) {
            Logger.getLogger(ViewShopperAgentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(String s :product_list){
            listScarcity.add(s);
        }
    }

    private void loadThreshold() {
        threshold=shopperAgent.getThreshold();
        this.thresholdTextField.setText(String.valueOf(threshold));
    }
}
