/*
 * VisitorsPanel.java
 *
 * Created on 4 novembre 2006, 15.53
 */

package it.unibo.homemanager.userinterfaces;

import it.unibo.homemanager.ServiceFactory;
import it.unibo.homemanager.tablemap.User;
import it.unibo.homemanager.tablemap.Visitor;
import it.unibo.homemanager.dbmanagement.*;
import it.unibo.homemanager.tablemap.ServicesInterfaces.VisitorServiceInterface;
import it.unibo.homemanager.util.Utilities;
import javax.swing.JOptionPane;

import java.util.Vector;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  admin
 */
public class VisitorsPanel extends javax.swing.JPanel {
    
    private MainPanel mp;
    private User u;
    private ServiceFactory sf;
    private VisitorServiceInterface vs;
    private Database database;
    private Visitor vis = null;
    
    /** Creates new form VisitorsPanel */
    public VisitorsPanel(MainPanel mp, ServiceFactory sf) {
        this.mp = mp;
        this.vs = sf.getVisitorServiceInterface();
	try {
	    this.database = sf.getDatabaseInterface();
	} catch (Exception ex) {
	    Logger.getLogger(VisitorsPanel.class.getName()).log(Level.SEVERE, null, ex);
	}
        initComponents();
    }
    
    protected void init(User usr) {
        u = usr;
        lbRes.setText("");
        tfNameMod.setText("");
        tfSNameMod.setText("");
        tfName.setText("");
        tfSName.setText("");
        fillList();
        list1.setFont(new java.awt.Font("Courier New",java.awt.Font.PLAIN,13));
        //
        if(!isVisible())
            setVisible(true);
    }
    
    private void fillList() {
        try {
            list1.removeAll();
            Vector visitors = vs.getVisitors(database.getDatabase());
            for(int i=0;i<visitors.size();i++) {
                Visitor v = (Visitor)visitors.elementAt(i);
                list1.add(v.toString());
            }
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
    }
    
    protected void hidePanel() {
        if(isVisible())
            setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btMenu = new javax.swing.JButton();
        btLogOut = new javax.swing.JButton();
        btModify = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        insertPanel = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();
        tfSName = new javax.swing.JTextField();
        btInsert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbRes = new javax.swing.JLabel();
        list1 = new java.awt.List();
        modifyPanel = new javax.swing.JPanel();
        tfSNameMod = new javax.swing.JTextField();
        tfNameMod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btOkModify = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(204, 204, 255));
        setFont(new java.awt.Font("Courier New", 0, 13));
        setMaximumSize(new java.awt.Dimension(538, 343));
        setMinimumSize(new java.awt.Dimension(538, 343));
        setPreferredSize(new java.awt.Dimension(538, 343));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Manage Visitors list:");

        btMenu.setFont(new java.awt.Font("Courier New", 1, 14));
        btMenu.setForeground(new java.awt.Color(153, 0, 153));
        btMenu.setText("MENU");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });

        btLogOut.setFont(new java.awt.Font("Courier New", 1, 14));
        btLogOut.setForeground(new java.awt.Color(153, 0, 153));
        btLogOut.setText("LOG OUT");
        btLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogOutActionPerformed(evt);
            }
        });

        btModify.setFont(new java.awt.Font("Courier New", 1, 14));
        btModify.setForeground(new java.awt.Color(0, 102, 204));
        btModify.setText("MODIFY");
        btModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifyActionPerformed(evt);
            }
        });

        btDelete.setFont(new java.awt.Font("Courier New", 1, 14));
        btDelete.setForeground(new java.awt.Color(0, 102, 204));
        btDelete.setText("DELETE");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        insertPanel.setBackground(new java.awt.Color(153, 153, 255));
        insertPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        insertPanel.setFont(new java.awt.Font("Courier New", 0, 13));

        tfName.setFont(new java.awt.Font("Courier New", 0, 13));

        tfSName.setFont(new java.awt.Font("Courier New", 0, 13));

        btInsert.setFont(new java.awt.Font("Courier New", 1, 14));
        btInsert.setForeground(new java.awt.Color(51, 0, 102));
        btInsert.setText("ADD VISITOR");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 12));
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Firstname:");

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12));
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Surname:");
        jScrollPane1.setViewportView(modifyPanel);

        org.jdesktop.layout.GroupLayout insertPanelLayout = new org.jdesktop.layout.GroupLayout(insertPanel);
        insertPanel.setLayout(insertPanelLayout);
        insertPanelLayout.setHorizontalGroup(
            insertPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(insertPanelLayout.createSequentialGroup()
                .add(insertPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(insertPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(insertPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(tfSName)
                            .add(tfName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 192, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(insertPanelLayout.createSequentialGroup()
                        .add(42, 42, 42)
                        .add(btInsert)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        insertPanelLayout.setVerticalGroup(
            insertPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(insertPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tfName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tfSName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(btInsert)
                .add(26, 26, 26))
        );

        lbRes.setFont(new java.awt.Font("Courier New", 1, 12));
        lbRes.setForeground(new java.awt.Color(255, 0, 0));

        list1.setFont(new java.awt.Font("Courier New", 0, 12));
        list1.setForeground(new java.awt.Color(0, 0, 51));

        modifyPanel.setBackground(new java.awt.Color(0, 0, 153));
        modifyPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfSNameMod.setFont(new java.awt.Font("Courier New", 0, 13));

        tfNameMod.setFont(new java.awt.Font("Courier New", 0, 13));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 12));
        jLabel4.setForeground(new java.awt.Color(221, 220, 247));
        jLabel4.setText("Firstname:");

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 12));
        jLabel5.setForeground(new java.awt.Color(221, 220, 247));
        jLabel5.setText("Surname:");

        btOkModify.setFont(new java.awt.Font("Courier New", 1, 14));
        btOkModify.setForeground(new java.awt.Color(51, 0, 102));
        btOkModify.setText("OK");
        btOkModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkModifyActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout modifyPanelLayout = new org.jdesktop.layout.GroupLayout(modifyPanel);
        modifyPanel.setLayout(modifyPanelLayout);
        modifyPanelLayout.setHorizontalGroup(
            modifyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(modifyPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(modifyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(tfNameMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(modifyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(tfSNameMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btOkModify))
        );
        modifyPanelLayout.setVerticalGroup(
            modifyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(modifyPanelLayout.createSequentialGroup()
                .add(modifyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(modifyPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tfSNameMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tfNameMod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27))
            .add(modifyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(btOkModify, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 12));
        jLabel7.setText("Insert new Visitors or modify/delete those already present.");

       

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(lbRes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(10, 10, 10)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel7))
                                .add(layout.createSequentialGroup()
                                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 242, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(btMenu, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(btLogOut, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                .add(layout.createSequentialGroup()
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                            .add(btModify, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(btDelete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, list1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 239, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(insertPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .add(modifyPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btLogOut)
                    .add(btMenu))
                .add(8, 8, 8)
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbRes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    )
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(list1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btDelete)
                            .add(btModify)))
                    .add(insertPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(modifyPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btOkModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkModifyActionPerformed
        if(Utilities.isEmpty(tfNameMod.getText()) || Utilities.isEmpty(tfSNameMod.getText())) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Please insert both FIRSTNAME and SURNAME.",
                    "MISSING DATA",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            vis.fn = tfNameMod.getText();
            vis.sn = tfSNameMod.getText();
	    vs.updateVisitor(database.getDatabase(),vis);
            fillList();
            lbRes.setText("VISITOR SUCCESSFULLY UPDATED!");
            vis = null;
            tfNameMod.setText("");
            tfSNameMod.setText("");
        }
        catch (Exception ex) {
        ex.printStackTrace();
        }
    }//GEN-LAST:event_btOkModifyActionPerformed

    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed
        if(Utilities.isEmpty(tfName.getText()) || Utilities.isEmpty(tfSName.getText())) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Please insert both FIRSTNAME and SURNAME.",
                    "MISSING DATA",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            vs.insertVisitor(database.getDatabase(),tfName.getText(),tfSName.getText());
            lbRes.setText("NEW VISITOR "+tfName.getText()+" "+tfSName.getText()+" INSERTED!");
            fillList();
            tfName.setText("");
            tfSName.setText("");
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btInsertActionPerformed

    private void btModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifyActionPerformed
        if(list1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null,
                    "Please select a Visitor to modify.",
                    "MISSING SELECTION",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            StringTokenizer t = getTokens(list1.getSelectedItem());
            vis = vs.getVisitor(database.getDatabase(),t.nextToken(),t.nextToken());
            tfNameMod.setText(vis.fn);
            tfSNameMod.setText(vis.sn);
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btModifyActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        if(list1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null,
                    "Please select a Visitor to delete.",
                    "MISSING SELECTION",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Database db = database.getDatabase();
            StringTokenizer t = getTokens(list1.getSelectedItem());
            Visitor v = vs.getVisitor(db,t.nextToken(),t.nextToken());
            int choice = JOptionPane.showConfirmDialog(null,
                    "Do you really want to delete "+v.toString()+"?",
                    "DELETE CHECK",JOptionPane.OK_CANCEL_OPTION);
            if(choice == JOptionPane.OK_OPTION) {
                vs.deleteVisitor(db, v);
                lbRes.setText(v.toString()+" SUCCESSFULLY DELETED!");
                fillList();
            }
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogOutActionPerformed
        mp.logOut(evt);
    }//GEN-LAST:event_btLogOutActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        mp.loadInitRolePanel(u);
    }//GEN-LAST:event_btMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = this.tfName.getText()+this.tfSName.getText();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private StringTokenizer getTokens(String vis) {
        StringTokenizer t = new StringTokenizer(vis," ");
        return t;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btLogOut;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btModify;
    private javax.swing.JButton btOkModify;
    private javax.swing.JPanel insertPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbRes;
    private java.awt.List list1;
    private javax.swing.JPanel modifyPanel;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNameMod;
    private javax.swing.JTextField tfSName;
    private javax.swing.JTextField tfSNameMod;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
